language: generic
sudo: required
services:
  - docker 
    
before_install:
  - docker build -t svidalikerlan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true svidalikerlan/react-test npm run test -- --coverage

after_success:
  - docker build -t svidalikerlan/multi-client ./client
  - docker build -t svidalikerlan/multi-server ./server
  - docker build -t svidalikerlan/multi-worker ./worker
  - docker build -t svidalikerlan/multi-nginx ./nginx
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push to Docker Hub
  - docker push svidalikerlan/multi-client
  - docker push svidalikerlan/multi-server
  - docker push svidalikerlan/multi-worker
  - docker push svidalikerlan/multi-nginx