# DOCKER IMAGE FOR SIMPLEWEB
#
# Use an existing docker image as a base
FROM node:alpine

USER node

# Establishing working directory
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# (Optional) Download extra utilities to customize our base image

# Adding and installing project dependencies
COPY --chown=node:node package.json .
RUN npm install

# Adding project files to the working directory
COPY --chown=node:node . .

# Exposing ports

# Tell the image what to do when it starts as a container
CMD ["npm", "run", "start"]