# DOCKER IMAGE FOR SIMPLEWEB
#
# Use an existing docker image as a base
FROM nginx

# Establishing working directory

# (Optional) Download extra utilities to customize our base image

# Adding and installing project dependencies

# Adding project files to the working directory
COPY ./default_dev.conf /etc/nginx/conf.d/default.conf

# Exposing ports

# Tell the image what to do when it starts as a container
